### ISSUE TITLE
Build focal (3.8) wheels on focal

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/charmcraftcache-hub#111]
Currently, we're building focal/3.8 wheels on jammy using pyenv to install python 3.8

This is causing issues with the wheels linking to the incorrect .so files: https://github.com/canonical/pgbouncer-operator/issues/368#issuecomment-2370809121

We should build focal wheels on ubuntu 20.04 to fix this

Reported & traced by @dragomirp

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical drop a Jira pulse ticket to pickup this the next pulse(s). Tnx!
